cmake_minimum_required(VERSION 4.3)
project(Know_Your_Computer)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(Know_Your_Computer
        src/main.cpp
        include/system/component-reader.h
        include/system/CPU/proc-reader.h
        include/system/GPU/gpu-reader.h
        include/system/Motherboard/motherboard-reader.h
        src/system/CPU/proc-reader.cpp
        src/system/GPU/gpu-reader.cpp
        src/system/Motherboard/motherboard-reader.cpp
        src/system/component-reader.cpp
        src/system/GPU/intel-reader.cpp
        src/system/GPU/nvidia-reader.cpp
        src/system/GPU/amd-reader.cpp
        include/system/GPU/intel-reader.h
        include/system/GPU/nvidia-reader.h
        include/system/GPU/amd-reader.h
        include/system/Processes/process-reader.h
        src/system/Processes/process-reader.cpp
)

target_include_directories(Know_Your_Computer PRIVATE
        ${CMAKE_SOURCE_DIR}/include/system/CPU
        ${CMAKE_SOURCE_DIR}/include/system/GPU
        ${CMAKE_SOURCE_DIR}/include/system/Motherboard
        ${CMAKE_SOURCE_DIR}/include/system/Processes
        ${CMAKE_SOURCE_DIR}/include/system/
        ${CMAKE_SOURCE_DIR}/vendor/nvml
        ${CMAKE_SOURCE_DIR}/vendor/level-zero
)

target_link_libraries(Know_Your_Computer PRIVATE ${CMAKE_DL_LIBS})